version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ksrcce-app
    container_name: ksrcce-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - ksrcce-network
    depends_on:
      - db

  web:
    image: nginx:alpine
    container_name: ksrcce-web
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - ksrcce-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: ksrcce-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-cce}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_USER: ${DB_USERNAME:-root}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - ksrcce-network
    ports:
      - "33061:3306"

networks:
  ksrcce-network:
    driver: bridge

volumes:
  dbdata:
